package EventManagementSystem;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
*
* @author HP
*/
public class CustomerInfo1 extends javax.swing.JFrame {

   /**
    * Creates new form CustomerInfo1
    */
   public CustomerInfo1() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")                         
   private void initComponents() {

       jScrollPane1 = new javax.swing.JScrollPane();
       jTable1 = new javax.swing.JTable();
       jButton1 = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jTable1.setModel(new javax.swing.table.DefaultTableModel(
           new Object [][] {
               {null, null, null, null, null, null, null},
               {null, null, null, null, null, null, null},
               {null, null, null, null, null, null, null},
               {null, null, null, null, null, null, null}
           },
           new String [] {
               "UserName", "User ID", "Contact No.", "Email Address", "Event", "Deposit", "Event Status"
           }
       ));
       jScrollPane1.setViewportView(jTable1);

       jButton1.setText("BACK");
       jButton1.addMouseListener(new MouseAdapter() {
    	   @Override
    	   public void mouseClicked(MouseEvent e) {
    	   Dashboard1 register = new Dashboard1();
    	   register.setVisible(true);
    	   }
    	   });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(653, 653, 653)
               .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
           .addGroup(layout.createSequentialGroup()
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(0, 372, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(18, 18, 18)
               .addComponent(jButton1)
               .addContainerGap(220, Short.MAX_VALUE))
       );

       pack();
   }                       

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(CustomerInfo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(CustomerInfo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(CustomerInfo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(CustomerInfo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new CustomerInfo1().setVisible(true);
           }
       });
   }                    
   private javax.swing.JButton jButton1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable jTable1;                  
}