package EventManagementSystem;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
*
* @author HP
*/
public class EventDetails extends javax.swing.JFrame {

   /**
    * Creates new form EventDetails
    */
   public EventDetails() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jPanel1 = new javax.swing.JPanel();
       jLabel1 = new javax.swing.JLabel();
       jLabel5 = new javax.swing.JLabel();
       jLabel6 = new javax.swing.JLabel();
       jLabel7 = new javax.swing.JLabel();
       jLabel8 = new javax.swing.JLabel();
       jButton1 = new javax.swing.JButton();
       jScrollPane4 = new javax.swing.JScrollPane();
       jTextPane4 = new javax.swing.JTextPane();
       jScrollPane5 = new javax.swing.JScrollPane();
       jTextPane5 = new javax.swing.JTextPane();
       jButton2 = new javax.swing.JButton();
       jScrollPane6 = new javax.swing.JScrollPane();
       jTextPane6 = new javax.swing.JTextPane();
       jLabel9 = new javax.swing.JLabel();
       jTextField1 = new javax.swing.JTextField();
       jTextField3 = new javax.swing.JTextField();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jPanel1.setBackground(new java.awt.Color(51, 51, 51));

       jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
       jLabel1.setForeground(new java.awt.Color(255, 51, 0));
       jLabel1.setText("EVENT DETAILS");

       jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
       jLabel5.setForeground(new java.awt.Color(255, 51, 0));
       jLabel5.setText("Pending Amount");

       jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
       jLabel6.setForeground(new java.awt.Color(255, 51, 0));
       jLabel6.setText("Event Status");

       jLabel8.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
       jLabel8.setForeground(new java.awt.Color(255, 51, 0));
       jLabel8.setText("Amount Paid");

       jButton1.setText("BACK");
       jButton1.addMouseListener(new MouseAdapter() {
          	@Override
        	   public void mouseClicked(MouseEvent e) {
        	   Welcome register = new Welcome ();
        	   register.setVisible(true);
        	   }
        	   }); 

       jScrollPane4.setViewportView(jTextPane4);

       jScrollPane5.setViewportView(jTextPane5);

       jButton2.setText("SHOW");
       jButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
            Connection c = connection.connect();
            PreparedStatement p;
            ResultSet rs ;
            String User_ID = jTextField1.getText() ;
            try {
                String sql = "select * from EventDetails WHERE User_ID =?";
                assert c != null;
                p = c.prepareStatement(sql);
                p.setString(1,User_ID);
                rs = p.executeQuery();
                while (rs.next()) {
                    String EventStatus = rs.getString("Event_Status");
                    String AmountPaid = rs.getString("Amount_Paid");
                    String PendingAmount = rs.getString("Pending_Amount");
                    jTextPane6.setText(EventStatus);
                    jTextPane4.setText(AmountPaid);
                    jTextPane5.setText(PendingAmount);
                }
            } catch (SQLException e1) {
            
            	e1.printStackTrace();
            }
           }
       });

       jScrollPane6.setViewportView(jTextPane6);

       jLabel9.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
       jLabel9.setForeground(new java.awt.Color(255, 51, 0));
       jLabel9.setText("User ID");

       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                       .addGap(80, 80, 80)
                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel8)
                           .addComponent(jLabel6)
                           .addComponent(jLabel5)
                           .addComponent(jLabel9))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                           .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                           .addComponent(jTextField1))))
               .addContainerGap(132, Short.MAX_VALUE))
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGap(155, 155, 155)
                       .addComponent(jLabel1))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGap(171, 171, 171)
                       .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGap(187, 187, 187)
                       .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addContainerGap(189, Short.MAX_VALUE))
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addGap(52, 52, 52)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(26, 26, 26)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel9)
                   .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(17, 17, 17)
               .addComponent(jButton2)
               .addGap(27, 27, 27)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(jLabel6)
                       .addGap(28, 28, 28)
                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(jPanel1Layout.createSequentialGroup()
                               .addComponent(jLabel8)
                               .addGap(18, 18, 18)
                               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel5))
                               .addGap(19, 19, 19)
                               .addComponent(jLabel7)
                               .addGap(18, 18, 18)
                               .addComponent(jButton1))
                           .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                   .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(45, Short.MAX_VALUE))
       );

       jTextField3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField3ActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                   .addGap(208, 208, 208)
                   .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                   .addGap(209, 209, 209)))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(0, 156, Short.MAX_VALUE))
           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                   .addGap(185, 185, 185)
                   .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addContainerGap(371, Short.MAX_VALUE)))
       );

       pack();
   }// </editor-fold>                        

   private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new EventDetails().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane4;
   private javax.swing.JScrollPane jScrollPane5;
   private javax.swing.JScrollPane jScrollPane6;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField3;
   private javax.swing.JTextPane jTextPane4;
   private javax.swing.JTextPane jTextPane5;
   private javax.swing.JTextPane jTextPane6;
   // End of variables declaration                   
}