package EventManagementSystem;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
*
* @author HP
*/
public class Introduction1 extends javax.swing.JFrame {

   /**
    * Creates new form Introduction1
    */
   public Introduction1() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
                             
   private void initComponents() {

       jPanel1 = new javax.swing.JPanel();
       jButton2 = new javax.swing.JButton();
       jButton3 = new javax.swing.JButton();
       jLabel2 = new javax.swing.JLabel();
       jLabel3 = new javax.swing.JLabel();
       jPasswordField1 = new javax.swing.JPasswordField();
       jScrollPane1 = new javax.swing.JScrollPane();
       jTextPane1 = new javax.swing.JTextPane();
       jLabel4 = new javax.swing.JLabel();
       jScrollPane2 = new javax.swing.JScrollPane();
       jTextPane2 = new javax.swing.JTextPane();
       jLabel1 = new javax.swing.JLabel();
       jPanel2 = new javax.swing.JPanel();
       jButton4 = new javax.swing.JButton();
       jButton5 = new javax.swing.JButton();
       jLabel5 = new javax.swing.JLabel();
       jLabel6 = new javax.swing.JLabel();
       jLabel7 = new javax.swing.JLabel();
       jLabel8 = new javax.swing.JLabel();
       jLabel10 = new javax.swing.JLabel();
       jTextField1 = new javax.swing.JTextField();
       jTextField2 = new javax.swing.JTextField();
       jPasswordField3 = new javax.swing.JPasswordField();
       jLabel9 = new javax.swing.JLabel();

       jPanel1.setBackground(new java.awt.Color(0, 204, 204));
       jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

       jButton2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
       jButton2.setText("SIGN UP");
       jButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton2ActionPerformed(evt);
           }
       });

       jButton3.setFont(new java.awt.Font("Verdana", 1, 18));
       jButton3.setText("LOGIN");

       jLabel2.setFont(new java.awt.Font("Script MT Bold", 0, 24)); 
       jLabel2.setText("Username");

       jLabel3.setFont(new java.awt.Font("Script MT Bold", 0, 24)); 
       jLabel3.setText("Password");

       jPasswordField1.setText("jPasswordField1");

       jScrollPane1.setViewportView(jTextPane1);

       jLabel4.setFont(new java.awt.Font("Script MT Bold", 0, 24)); 
       jLabel4.setText("User ID");

       jScrollPane2.setViewportView(jTextPane2);

       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(jButton3)
                       .addGap(54, 54, 54)
                       .addComponent(jButton2))
                   .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                       .addGap(109, 109, 109)
                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                           .addComponent(jScrollPane1)
                           .addComponent(jScrollPane2))))
               .addGap(94, 94, 94))
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
               .addGap(50, 50, 50)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(44, 44, 44)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jScrollPane2))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(81, 81, 81)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGap(24, 24, 24))
       );

       jLabel1.setBackground(new java.awt.Color(0, 255, 204));
       jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 24));
       jLabel1.setForeground(new java.awt.Color(0, 153, 153));
       jLabel1.setText("LOGIN PAGE");

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jPanel2.setBackground(new java.awt.Color(51, 51, 51));
       jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

       jButton4.setFont(new java.awt.Font("Verdana", 1, 18));
       jButton4.setText("SIGN UP");
       jButton4.addMouseListener(new MouseAdapter() {
    	   @Override
    	   public void mouseClicked(MouseEvent e) {
    	   Registrationform register = new Registrationform();
    	   register.setVisible(true);
    	   }
    	   });
       jButton4.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton4ActionPerformed(evt);
           }
       });

       jButton5.setFont(new java.awt.Font("Verdana", 1, 18)); 
       jButton5.setText("LOGIN");
       jButton5.addMouseListener(new MouseAdapter() {
    	   @Override
    	   public void mouseClicked(MouseEvent e) {
    	   Welcome register = new  Welcome();
    	   register.setVisible(true);
    	   }
    	   });

       jLabel5.setFont(new java.awt.Font("Serif", 0, 24)); 
       jLabel5.setForeground(new java.awt.Color(255, 0, 0));
       jLabel5.setText("Username");

       jLabel6.setFont(new java.awt.Font("Serif", 0, 24)); 
       jLabel6.setForeground(new java.awt.Color(255, 51, 0));
       jLabel6.setText("Password");

       jLabel7.setFont(new java.awt.Font("Serif", 0, 24)); 
       jLabel7.setForeground(new java.awt.Color(255, 51, 0));
       jLabel7.setText("User ID");

       jLabel8.setBackground(new java.awt.Color(0, 255, 204));
       jLabel8.setFont(new java.awt.Font("Cooper Black", 1, 24)); 
       jLabel8.setForeground(new java.awt.Color(255, 51, 0));
       jLabel8.setText("LOGIN PAGE");

       jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); 
       jLabel10.setForeground(new java.awt.Color(255, 255, 255));
       jLabel10.setText("Make Your Every Moment Memorable!!!");

       jPasswordField3.setText("jPasswordField3");

       javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
       jPanel2.setLayout(jPanel2Layout);
       jPanel2Layout.setHorizontalGroup(
           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
               .addGap(109, 109, 109)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(78, 78, 78)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jTextField1)
                   .addComponent(jTextField2)
                   .addComponent(jPasswordField3))
               .addGap(94, 94, 94))
           .addGroup(jPanel2Layout.createSequentialGroup()
               .addGap(184, 184, 184)
               .addComponent(jButton5)
               .addGap(49, 49, 49)
               .addComponent(jButton4)
               .addContainerGap(127, Short.MAX_VALUE))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                       .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(22, 22, 22))
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                       .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(190, 190, 190))))
       );
       jPanel2Layout.setVerticalGroup(
           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
               .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(16, 16, 16)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(44, 44, 44)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel7)
                   .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel6)
                   .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(59, 59, 59)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jButton5)
                   .addComponent(jButton4))
               .addGap(18, 18, 18)
               .addComponent(jLabel10)
               .addGap(19, 19, 19))
       );

       jLabel9.setFont(new java.awt.Font("Snap ITC", 1, 36)); 
       jLabel9.setForeground(new java.awt.Color(255, 0, 0));
       jLabel9.setText("EVENT MANAGEMENT SYSTEM");

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(213, 213, 213)
                       .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(114, 114, 114)
                       .addComponent(jLabel9)))
               .addContainerGap(335, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(16, Short.MAX_VALUE))
       );

       pack();
   }                        

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
   }                                        

   private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
   }                                        

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(Introduction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(Introduction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(Introduction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(Introduction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new Introduction1().setVisible(true);
           }
       });
   }                     
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton5;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPasswordField jPasswordField1;
   private javax.swing.JPasswordField jPasswordField3;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField2;
   private javax.swing.JTextPane jTextPane1;
   private javax.swing.JTextPane jTextPane2;
}
